### ISSUE TITLE
Discuss: Should it be possible to position cards off-screen? If yes, how?

### ISSUE THREAD

**Issue by kleinfreund** [noopkat/electric-io#125]
In its current form, electric-io’s cards can be moved off-screen with the mouse. With #124 merged, that is true for keyboard, too.

Is this exptected behavior?

There are more or less three options:

- Allow cards to be moved off-screen (current behavior)
- Don’t allow cards to be moved off-screen
- Allow cards to be moved off-screen on the vertical axis only

I bring this up because one could make the point that the dashboard gets rather hard to access if we continue to allow cards to be positioned wherever. The Web Content Accessibility Guidelines have a success criterion called [Reflow](https://www.w3.org/TR/2018/REC-WCAG21-20180605/#reflow) that deals with this question in the context of a web page with a more typical layout (i.e. boxes are stacked on the block axis, creating a vertically-overflowing page).

**Comment by underscoredotspace** [comment]
My web-based [portfolio](https://messy.cloud) uses windows that are logically similar to our card concept. There I have chosen to not allow windows to leave the viewport. This does however increase the logic required in the move and size functions, and we'd need to handle viewport resizing/zooming. 

In my app there is a minimum height and width for a window. When the viewport is resized the window's size is reduced until it reaches the minimum, then the position is moved up and left until it reaches (0,0). Using the viewport size as a trigger also handles zoom-in which gives consistent (and logical) behaviour. [Testing this out has caused me to notice some bugs, so thanks for triggering this thought 😆]

Perhaps the easiest route though (from a "logic required" viewpoint) would be to allow cards to be moved anywhere and provide scroll bars. This option would have the added benefit of making the app more usable on small screens too. 

Despite the wall of text I've just put in here, I don't have a strong opinion. Just thought it would be of value to share my experience.

**Comment by kleinfreund** [comment]
@underscoredotspace Your portfolio also provides a clue for why free positioning of cards should be possible: All OSes I know allow windows to be moved out of their viewport freely. Atleast, when using the mouse to drag windows around.

**Comment by noopkat** [comment]
@underscoredotspace this is off topic but your portfolio site is very cool!

**Comment by noopkat** [comment]
I like @mtheoryx's idea of "bouncing" the card back if dragged or keyboard moved off the top or left edges of the screen. I think right and bottom edges should just extend the dashboard itself. Thoughts?

**Comment by mjasnowski** [comment]
I like the idea of bouncing cards back, but wonder what the user experience would be when accessing cards that are placed at far lower right of an extended canvas. Presumably you would scroll/pan to reach them but then when you drag a card back up to the top left would they bounce back again? Or would it pan the canvas until the top left of the canvas is reached (0,0) and then bounce back?  

I understand it might go against the flexibility if placing the cards anywhere, but what about having a tray of sorts they get placed in (w/icon) that would open if dragged off screen ?

**Comment by underscoredotspace** [comment]
Since electric-io works on mobile browsers, should we add the ability to move cards with touch? Currently I think that's the only thing (apart from very minor layout things) that isn't at parity with non-touch browsers.

**Comment by kleinfreund** [comment]
@underscoredotspace Yes, absolutely. In fact, I would consider this a bug right now. By properly separating functions for pointer-based movement and the registration of mouse-based and touch-based event listeners, this should be fairly easy to fix. I’ve done something similar recently and might be able to drop it into #127 if I get the chance until tomorrow. Also, thanks for pointing this out. I noticed this while working on my pull request, but didn’t report it as a bug or mention it. My bad.

**Comment by noopkat** [comment]
closing this as it was addressed in #127  🎉 

![bitmoji](https://render.bitstrips.com/v2/cpanel/738f5341-51b2-4de7-b84a-daced4ed9e7e-8016a622-e09b-4505-8856-7726a074b1f9-v1.png?transparent=1&palette=1&width=246)
