### ISSUE TITLE
Document how to migrate dashboard settings from one app to another

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#13]
This should go in the README.md file.

Essentially to migrate your dashboard layout settings what you do is copy your dashboard.json file from one electric-io app to another, placing it in the `.data` directory.

**Comment by davidk** [comment]
Hello there,
Will give this a go!

**Comment by davidk** [comment]
Issue #53 (Windows specific) is now up for grabs, so this is a friendly wave to close this one :star2:

**Comment by noopkat** [comment]
@davidk 🙌
