### ISSUE TITLE
In card edit mode, changes lost when card is moved

### ISSUE THREAD

**Issue by underscoredotspace** [noopkat/electric-io#130]
### Description

In edit mode, text fields revert to pre-edited state when card is dragged

### Steps to reproduce

- Select `edit` on a card
- Change a text field (Title, Message Payload or Button Text)
- Drag card to a new position

The other `select` elements are unaffected by this issue.

**Comment by underscoredotspace** [comment]
Actually, changes to other text boxes are lost when **any** card is dragged. In settings unsaved changes to all text fields except colour are reverted.

**Comment by kleinfreund** [comment]
@underscoredotspace Could you do me the favor of trying to replicate this with the changes in made #127? I think I noticed this and fixed it there.

**Comment by underscoredotspace** [comment]
@kleinfreund The issue seems to remain, but the card refuses to move in edit mode. Editing a text field and clicking away from it refocuses the textbox and reverts the field also. Again on the textbox fields are affected, and select/textareas are fine.

**Comment by noopkat** [comment]
closing this as per @kleinfreund's advice 💪
