### ISSUE TITLE
Improve html landmarks for page

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#133]
Continuing the [landmark discussion](https://github.com/noopkat/electric-io/issues/1#issuecomment-508914904) from #1 

Making the main app div a `<main>` element would help. Perhaps the settings can also be assigned a role that makes sense as well?

**Comment by kleinfreund** [comment]
Certainly, we should use the `main` element to mark what our primary content is. In our case, I think that the collection of cards form our dashboard and the dashboard would be our primary (main) content.

As for the settings, I could see the `aside` element being appropriate, but I’m not entirely convinced. As far as I know, there isn’t a more appropriate way to identify a section of settings. With that being said, `section` doesn’t make sense as we only ever have one section of settings, so I don’t think that helps.

I marked this as a “good first issue”.

**Comment by Mrduckie** [comment]
Is this issue still open? I noticed it was created a while ago and that a main element was already in use so I wanted to check.

**Comment by kleinfreund** [comment]
@Mrduckie Good question. The `main` element is indeed already there and placed correctly, I think. I don’t have anything else in mind specifically that we should improve in terms of HTML landmarks.

So if there’s something you or someone else can think of, we’re all ears. But I would also be fine with closing this issue there isn’t a concrete action we can take right now.

**Comment by noopkat** [comment]
👍 I'm all for closing this issue and opening any new ones needed based on other a11y improvements we could work on.
