### ISSUE TITLE
Color picker preview <div> z-index

### ISSUE THREAD

**Issue by N1Nxx** [noopkat/electric-io#141]
The color picker preview div in the App settings and card settings is displayed above other cards (couldn't replicate on some cards)

![Screenshot 2019-07-16 at 19 01 20](https://user-images.githubusercontent.com/52948073/61281030-443daa80-a7fc-11e9-88b5-55f955780903.png)
![Screenshot 2019-07-16 at 19 01 31](https://user-images.githubusercontent.com/52948073/61281031-443daa80-a7fc-11e9-9e09-207084c39fd0.png)

**Comment by jeffnhorner** [comment]
Hey @N1Nxx and noopcrew! I went ahead and created a pr for this fix but I'm wondering if there was a specific reason for this z-index to be set? I tagged @kleinfreund in the pr to take a look so we could have a conversation about it before this is (potentially) merged in 😊 

Good find though for sure! ✋

**Comment by kleinfreund** [comment]
I merged that PR just now. I think I had this `z-index` in there because there was another pseudo element in there that needed to be stacked somehow. Thank you for looking into this. :)

**Comment by jeffnhorner** [comment]
Oh I see, well thanks for reviewing so quickly. Np man!
