### ISSUE TITLE
Optimise vendor bundle size 

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#144]
Hello,

I did some analysis on what's causing our vendor bundle size to be so large.
The low hanging fruit I found was Chart.js. I pointed at the minified bundle instead of the full dist and saved over 200KB 😱 

The main difference is that the full dist includes moment.js and we don't use the dependent features in chart.js currently.

I think we can even go one better and look into using [Chartist](https://gionkunz.github.io/chartist-js/index.html) instead and knock that vendor bundle down even more.

If we're on board, I can work on this optimisation over the next couple of weeks.

**Comment by kleinfreund** [comment]
Adding the following rule to the `plugins` key in the Webpack configuration shaves off the locales from Moment.js:

```
new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
```

Adding the following entry to the configuration removes all of Moment.js but also breaks the `LineChartCard`:

```
externals: {
  moment: "moment"
}
```

Comparison of our bundle size with Chart.js:

| Technique    | Bundle size    |
|--------------|----------------|
| Before       | main (732 KiB) |
| IgnorePlugin | main (552 KiB) |
| externals    | main (500 KiB) |

Comparison of Chart.js’ and Chartist’s bundle size:

| Package  | Minified | Minified + Gzip |
|----------|----------|-----------------|
| Chartist | 38.6 kB  |  11.4 kB        |
| Chart.js | 385.1 kB | 112.1 kB        |

😱😱😱

@noopkat Did you try something else?

**Comment by noopkat** [comment]
@kleinfreund I didn't ignore the bundle in the webpack config, rather I setup a new alias to resolve to the smaller chart.js bundle and that seemed to not break the linechart card's functionality. It was a shallow experiment to see how much moment.js was adding to the overall size.

Now that I have internet again, I just implemented the replacement of chart.js with chartist in a new branch and will open a pull request once I neaten it up a little bit.
