### ISSUE TITLE
Link to device method docs in readme

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#15]
The button card section in the readme mentions device methods casually but it should also link to an appropriate Azure docs location that explains what device methods are with regard to using them with Azure IoT Hub.

[This is probably the right docs page](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods) to link to but if there's a better one you can find let me know!

**Comment by mpaarating** [comment]
I'll snag this one!
