### ISSUE TITLE
Managing Dependencies with Renovate

### ISSUE THREAD

**Issue by lannonbr** [noopkat/electric-io#165]
So with #161 just merged, [Renovate](https://github.com/renovatebot/renovate) was added to this project. It will work alongside your package.json and update dependencies automatically and send PRs. This on top of Azure Pipelines will allow a nice system so when Renovate creates a new PR, the CI will run and then we can have some clarity that the dependency update is sucessful.

That said, with about 50 direct deps / devdeps, this can possibly push a lot of PRs. Renovate has a lot of [Config options](https://docs.renovatebot.com/configuration-options/) so I was going to open this issue just to get a discussion rolling on how renovate should function on this project.

**Comment by MichaelE1** [comment]
Great issue. I had a quick look in Azure Pipelines and it seems that Suz has already been API rate limited 😬. https://dev.azure.com/noopkat/electric-io/_build/results?buildId=212&view=results

I don't know much about Renovate, but it seems possible to [group all updates together](https://docs.renovatebot.com/presets-group/#groupall). That could help reduce the API calls and PRs (& notifications!).

**Comment by benhalverson** [comment]
I like the idea of grouping the updates in renovate that's the one thing that annoys me in my repos
