### ISSUE TITLE
Duplicate card IDs

### ISSUE THREAD

**Issue by MichaelE1** [noopkat/electric-io#19]
Hi @noopkat ,

First of all, awesome project. I really dig it.

I've found a small bug related to creating new cards. If you create two cards of the same type, they are assigned the same ID. In console you will see a [Vue warn]. 

![vuewarn](https://user-images.githubusercontent.com/21051488/38840116-5d909f02-4221-11e8-84d6-5e12907fb4fb.png)

As they have the same ID, if you delete one card it will delete both. It also seems that if you try to edit the second card, the first card will be edited. I tried working on a solution but I'm still new to Vue :disappointed: 

Happy to provide more details if needed. Tested on Chrome v65.

**Comment by noopkat** [comment]
thanks for reporting this! I wonder why it's creating the same id 🤔 
I'll let you know if I find anything 🙇‍♀️

**Comment by noopkat** [comment]
ok I'm pretty sure I found the issue. It came down to a classic JavaScript issue with references to existing objects and not actually creating a copy of it first 😄 
Let me know if the pull request makes sense - #20 

In the meantime, is there anything I could do to help make this project easier to grok for those who are new to Vue? I welcome your thoughts.

**Comment by MichaelE1** [comment]
Yes, that PR has solved it :tada: 

I've found the project on the whole quite approachable. Even with my minimal Vue experience I was still able to narrow down where the issue was, I just wasn't entirely sure on the solution during the time I spent on it. 

At the end of the day you have to require some prerequisite knowledge, and I don't feel that the coding style or file structure of the project is in anyway impeding that. The documentation for getting up and running was :100:

**Comment by noopkat** [comment]
@MichaelE1 that's really great to hear! Thanks for the feedback 😄 

Shout out if you have any further questions. I'll close this issue now as it's confirmed fixed.
