### ISSUE TITLE
Crashing due to vue-template-compiler and vue having different versions

### ISSUE THREAD

**Issue by C0ffeeCode** [noopkat/electric-io#193]
# Problem
The application does not launch due to "vue-template-compiler" version (2.6.11), not matching "vue" version (2.6.10).

# Impact
Application crashes while starting.

# Solution
Upgrade "vue" version or downgrade "vue-template-compiler". (Upgrading is probably better)

**Comment by C0ffeeCode** [comment]
#194

**Comment by kleinfreund** [comment]
Closed in https://github.com/noopkat/electric-io/pull/194.
