### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#2]
Current mobile support is not great.
Please check out the contributing guide in this repo for some ideas 💡

**Comment by jam3sn** [comment]
How do you feel about us dropping `absolute` so they all stack? We'd need to move the widths into classes so they can also become `width: 100%`, however, I'm not sure on the knock-on effect with the graphs until I have a deeper look.

**Comment by kleinfreund** [comment]
@jam3sn Indeed, cards should stack on small screens. That’s pretty much the only way. As long as users have to access content by scrolling in two dimensions, it won’t be a nice experience.

**Comment by noopkat** [comment]
totally agree and love the idea!

**Comment by jam3sn** [comment]
So I've made a quick update for basic mobile support: https://github.com/noopkat/electric-io/pull/118

**Comment by noopkat** [comment]
now closing this! 🎉 🎉 🎉 🎉
