### ISSUE TITLE
Value-dependent colour gradient

### ISSUE THREAD

**Issue by tkoster** [noopkat/electric-io#207]
How do folks feel about a colour gradient mode for the **number card**?

![colourgradient.gif](https://user-images.githubusercontent.com/9063335/79248576-58175980-7ebf-11ea-90be-9972c4eb8c19.gif)

I'm a bit stuck for ideas on how to fit it into the settings view though. Both horizontal and vertical layouts make the card much too big imo.

![colourgradientsettings.png](https://user-images.githubusercontent.com/9063335/79248921-d673fb80-7ebf-11ea-97c7-8f410047c5c2.png)

**Comment by kleinfreund** [comment]
We can think about hiding the color picker by default or at least one of them. The no-fuzz approach would be wrapping it in a details/summary element combo.

Also, Suz’s room is almost boiling if those are degree celsius. :hot_face: :hot_pepper:

**Comment by tkoster** [comment]
It's not over by much :joy:
![image](https://user-images.githubusercontent.com/9063335/79254714-7b92d200-7ec8-11ea-9ee7-44c4f47b34d3.png)

**Comment by tkoster** [comment]
Do you mean something like this?

![electricio-gradient-settings-2](https://user-images.githubusercontent.com/9063335/79446244-43eb6d80-8021-11ea-8040-4c30762baebb.gif)

- one colour picker is visible
- visually, the picker displays/sets whichever colour (low or high) that last had focus
- when tabbing, the fields are visited in this order: low value, low colour, high value, high colour

**Comment by kleinfreund** [comment]
Do I understand the GIF correctly that the color picker is made visible based on which of the two value text input fields was focused last?

I think that’s not super clear to someone who doesn’t know. There should be a clear interaction that toggles between the two color pickers. If I’m satisfied with the current setting of the “high value” field, I might never click into it and realize that I can change its associated color.

Let me try to illustrate what I suggested above with the details/summary elements:

---

## Settings

[the first few form controls]

Low value
[40_________]

<details>
<summary>Select low value color</summary>
[Low value color picker here]
</details>

High value
[80_________]

<details>
<summary>Select high value color</summary>
[High value color picker here]
</details>

[Save]
[Cancel]

---

Both color pickers would then be hidden from view by default.

**Comment by tkoster** [comment]
You are correct. I'm trying to balance screen real estate with the desire to have low number of clicks/keyboard interactions to get to specific controls, and I agree that clarity if often the thing that is traded away when optimising for those.

I'll try your suggestion and some more options.

**Comment by tkoster** [comment]
Oh and I'm trying to avoid the card from resizing too much while interacting with the form. I feel that's the most difficult constraint to satisfy.

**Comment by kleinfreund** [comment]
> I'm trying to avoid the card from resizing too much while interacting with the form.

While I see how that’s nice to have, I don’t think it’s a necessary constraint. The primary criteria, in my opinion, is ease of use including how well users are able to understand what they’re supposed to do and that they can do something in the first place.

**Comment by tkoster** [comment]
@tkoster :
> I'm trying to avoid the card from resizing too much while interacting with the form.

@kleinfreund :
> don’t think it’s a necessary constraint  ... primary criteria, in my opinion, is ease of use including how well users are able to understand what they’re supposed to do

Good to know.

In that case, here is a mock of my interpretation of your suggestion. I went with a fly-out card instead of an accordion. I thought I wouldn't like it but I do really like that the interactive elements on the form do not move around while the form is open.

![electricio-gradient-settings-3-popout](https://user-images.githubusercontent.com/9063335/79643661-68914200-81e7-11ea-875f-f6558b9b96ff.gif)

Some notes:

- The colour picker updates the value immediately, as before, which I've chosen to "preview" using the button colour.
- I'm not sure if my use of the buttons like this fits the design language of Electric I/O because buttons like this are usually actions.
- You do not need to dismiss the picker to save, cancel, or any other interaction with the form. However, not having an X to dismiss it seemed off so I added it.
- In the DOM, the colour picker is located just after the colour button. If the picker is visible, tab focus enters the picker after leaving the colour button, then goes back to the form. This might seem odd for sighted users who see the picker as a separate "window", but this order makes sense to me given that the fly-out is not modal.
- I know I'm mixing "Sentence case" with "Title Case" in this gif, sorry about that.

**Comment by noopkat** [comment]
omg yes I would love this feature! I also really appreciate how much prototyping work went into this 🥇 Thank you. I agree with the popout card proposal 💯 

![boy dancing and saying "hell yeah"](https://media.giphy.com/media/dkGhBWE3SyzXW/giphy.gif)
