### ISSUE TITLE
Route tests fail when not simulating

### ISSUE THREAD

**Issue by tkoster** [noopkat/electric-io#210]
I encountered the 404 issue that @noopkat had on the weekend running the unit tests. I believe this is what is happening:

When running the routes unit tests, `server.js` attempts to connect to the real IoT Hub if your `.env` file says so. The tests even print the `console.log` lines during hub startup. However, the _live hub_ fails to start and throws exceptions. I can reliably reproduce and fix the issue by switching between my `.env` file and the default `.env` file.

The environment affects the unit tests at runtime - we should aim to make the tests immune to the environment.

**Comment by tkoster** [comment]
More info:

The `startHubServer` function initialises the hub before registering any routes with express (presumably for the good reason that the handlers need to be injected with the appropriate hub service). If initialising the hub throws an exception, the routes are not initialised.

A quick fix might be to completely ignore `.env` and force simulation mode when `NODE_ENV` is `test`, similar to how the HTTP server start is elided.

However, the root cause seems to be that `server.js` is not really a reusable module that one can "require" (as the tests do), but rather is the "main" of the Node app. What happens when you "require" it is quite nondeterministic: it changes its behaviour drastically depending on the environment.

A more permanent fix might be to reduce the nondeterminism in these functions by changing references to the environment variables into formal parameters that can be controlled by the tests, and then move the functions into a module that can be required by the tests without these side-effects.

**Comment by tkoster** [comment]
Related to this: I noticed that the route tests also print lines saying an existing dashboard file was found and loaded. This is another source of potential nondeterminism that we should try to remove from the tests.

**Comment by noopkat** [comment]
👍 💯 to all of this

**Comment by tkoster** [comment]
I'll close this since #221 is merged and addresses this.

We can create a separate issue if dashboard files become a problem for tests. (I'm not convinced they currently are.)
