### ISSUE TITLE
Simulation UI status callout

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#22]
It would be nice to have a small status near top of the dashboard UI making it clear that you're simulating data when in simulating mode. I want to leave the Glitch app in simulation mode instead of hosting telemetry from a real IoT Hub, but make it clear that it's not 'real' data coming in.

When folks remix the app it won't start up in simulator mode so there's no worry about it persisting.

**Comment by escherina** [comment]
I can take this one on. 😊
