### ISSUE TITLE
Color audit for ally

### ISSUE THREAD

**Issue by mtheoryx** [noopkat/electric-io#27]
Related to #1 

Colors and color contrast is an important issue for visually-impaired or visually-sensitive issues.

This ticket is for remediation of some of the colors, specifically the green/red success/error messages to comply with color/contrast best practices.

This can be tested in chrome with an accessibility audit, or via a few other npm dependencies.

**Comment by dotproto** [comment]
@noopkat noted during her stream that she's targeting contrast level AA. See https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html for additional details.

**Comment by noopkat** [comment]
Thank you David and Simeon! 🙇🏼‍♀️

**Comment by escherina** [comment]
I've completed a colour audit as part of #1 - results are in that issue.
