### ISSUE TITLE
Thoughts on a Code of Conduct doc?

### ISSUE THREAD

**Issue by mtheoryx** [noopkat/electric-io#36]
Github has a pretty decent template that you can use, and it only requires a contact email for where complaints can be directed.

Personally, I prefer having these, but I know there are other opinions. Just want to get the community's thoughts on this addition.

**Comment by mpaarating** [comment]
I'd love to see one. I've definitely found them helpful in the past.

**Comment by atbuzz** [comment]
Sounds like a great idea!

**Comment by noopkat** [comment]
Hi folks! This is a great idea @mtheoryx. What do y'all think of using the same [code of conduct on avrgirl-arduino](https://github.com/noopkat/avrgirl-arduino/blob/master/CODE_OF_CONDUCT.md) for this project?

**Comment by mpaarating** [comment]
That looks good to me! @escherina How does that look to you?

**Comment by atbuzz** [comment]
Sounds excellent, @noopkat!

By the way, I love your streams so much!

**Comment by atbuzz** [comment]
I'll pull request a code of conduct.

**Comment by atbuzz** [comment]
Here: #38

**Comment by atbuzz** [comment]
It uses the code of conduct from avrgirl-arduino.

**Comment by escherina** [comment]
Closed with #2323d67 🎉

**Comment by noopkat** [comment]
thanks everyone!
