### ISSUE TITLE
Keyboard control alternative for card positioning

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#4]
Drag and drop is not accessible without a mouse or pointer device.

I suggest creating a 'move' button that only appears when a card is tabbed to (like 'skip to content' style buttons on websites). Activating this button will allow arrows on the keyboard to be used for moving the card left and right. Hitting the escape key will stop the moving.

**Comment by jam3sn** [comment]
Might be cool to also allow the use of SHIFT + Arrow to move by 10px or more like in most design programs.

**Comment by noopkat** [comment]
@jam3sn this is a great idea thank you! 💡

**Comment by kleinfreund** [comment]
I’m working on this.

I have a basic prototype ready implementing keyboard navigation as per @noopkat’s suggestion of using a toggle button to toggle a keyboard navigation mode for a particular card. Alternatively, we could make cards focusable themselves and allow keyboard navigation when a card has focus.

Another point of consideration is the choice between one global event listener for `keydown` events or per-card event listeners. The former has the problem of requiring additional code in the `main.js` file (setting up the event listener, etc.). I think the latter approach might eventually lead to a more idiomatic Vue style as the navigation code can be contained within the card component. I’ll see what ends up being the simpler code.

**Comment by noopkat** [comment]
we can now close this thanks to #124 🎉
