### ISSUE TITLE
Clarify supported NodeJS version

### ISSUE THREAD

**Issue by mtheoryx** [noopkat/electric-io#40]
From the readme, it is unclear what version of Node is required for the project.

I propose:

1. Add the supported version to the readme
2. Add the version in package.json under "engines" and "enginesStrict"
3. Using the correct base image for Docker.

I'm working on task 3 now... I really just need a definitive decision from the maintainers on where our base node version will start.

I'm happy to PR this once we make a decision.

Cheers!

**Comment by escherina** [comment]
Great idea! In the [contributing guide](https://github.com/noopkat/electric-io/blob/master/CONTRIBUTING.md), it says that NodeJS 4+ is required. However, the app will ultimately run on Glitch, which, [looking at their FAQ](https://glitch.com/faq#node), only goes down to version 6.0.0 (https://nodeversions.glitch.me/) - so maybe we could set 6.0.0 as the minimum version? What do you think, @noopkat?

**Comment by mtheoryx** [comment]
Interestingly, in the package.json, we currently have

```json
	"engines": {
		"node": "8"
	}
```

So I'm not sure if 4 was the target, or where the 8 came form.

I think, like browsers, "current + (N - 1)" could work. So active LTS is 8.x "carbon" and Maintenance LTS is 6.x "Boron" https://github.com/nodejs/Release#release-schedule

What do you think? Current, plus one version behind or maintenance?

**Comment by mtheoryx** [comment]
I included the node version updates and clarification in my PR. I needed to specify a known good node version for the base Docker image anyway :) I'll close this issue!
