### ISSUE TITLE
To check in dist files, or to not check in dist files?

### ISSUE THREAD

**Issue by mtheoryx** [noopkat/electric-io#41]
As I'm working, I'm noticing that public/js/dist/application.js keeps having minor changes. I mean minor, it's single-letter variable names when the generation and minification is done.

So... what do you all think?

I generally do not check generated files into a repo, but this isn't my repo. It's OUR repo :)

When it comes time to make "a build" the artifacts can be made and zipped. And we can make a hook for npm publishing that will generate those files for the publishing time. So in git, we can ignore dist files, but in our npmignore, we simply don't ignore the dist files. Found this that is a good example:

https://stackoverflow.com/questions/31642477/how-to-publish-a-npm-package-with-distribution-files

**Comment by mpaarating** [comment]
I agree with your sentiment and actually have two different PRs with it in there. I think that @noopkat gave it the ok in one of my PRs. I like the idea of publish a package and that seems elegant enough when the time comes.

**Comment by mtheoryx** [comment]
Fantastic, look forward to seeing those ignores get merged in. I'll close this one then. Cheers!
