### ISSUE TITLE
Add .editorconfig file to project

### ISSUE THREAD

**Issue by escherina** [noopkat/electric-io#43]
Having a [.editorconfig file](http://editorconfig.org/) might be helpful for contributors whose IDEs can auto-format on save (like mine! 😄).

.editorconfig supports the following settings:
- `indent_style`: `tab` or `space`
- `indent_size`: e.g. `2` or `4` spaces
- `end_of_line`: `lf`, `cr`, or `crlf`
- `charset`: set to `latin1`, `utf-8`, `utf-8-bom`, `utf-16be` or `utf-16le` to control the character set.
- `trim_trailing_whitespace`: setting to `true` will remove any whitespace characters preceding newline characters
- `insert_final_newline`: setting to `true` ensures that files end with a newline when saving

Looking at the project files, it seems that these are the formatting settings:
- `indent_style`: `space`
- `indent_size`: `2`
- `end_of_line`: `lf`
- `charset`: `utf-8`
- `trim_trailing_whitespace`: `true`, I think?
- `insert_final_newline`: `true`

**Comment by mtheoryx** [comment]
Interesting idea. I have mixed feelings about some of these things (more below, and would love to hear your thoughts), but whatever the project thinks is the best way forward, I can get behind :)

- A standard has to be decided upon, and usually, that's a team thing
- Linters are good, but can be annoying (we have a callout that we aren't using a linter here)
- Auto-formatters can be equally annoying when it runs live as you're trying to just work something out
- Alternatives are git hooks (pre commit, pre push, etc) to format code that may be less invasive

**Comment by escherina** [comment]
Thank you for the thoughts, @mtheoryx! I agree with you that linting and anything that invasively changes code would be out of place for this project.

However, a .editorconfig file is more static than a linting setup, more of an convenience for contributors: if your IDE doesn't have an auto-format on save setting, or doesn't recognise .editorconfig files by default, the .editorconfig file won't do anything. And for contributors whose IDEs are set up to use it, it helps avoid extensive commit changes caused by accidentally reformatting project files. Its settings are to do with whitespace/line endings only.

There's definitely a conversation to be had around standards! 😄 In this case, I would say we wouldn't need to use all the settings. The most important ones in terms of formatting are the indent style/size and the line endings. I'm happy with any indent style/size, but since this is @noopkat's project, the existing indent of 2 spaces seems fine. There also seems no pressing reason to change the line endings from LF.

I admit that this is definitely a convenience issue for me, as I have to turn off VS Code's auto-formatting when I work on electric-io, and I really miss it! 😄 If it's not a priority for the project, no problem at all.

**Comment by mpaarating** [comment]
I'm a fan of this idea as I keep formatting EVERYTHING when using VS Code and making PRs look gigantic (then spend my time to fix them in vim). Those settings are 💯 to me! 

Agreed with @mtheoryx that for @noopkat or someone that happens to be streaming this, it might be a bit invasive when the changes occur, although I think its not a huge issue as I've paid for content that has had that happen during the stream.

OTOH git hooks would apply to everyone. If there's one thing I love, its forcing my code style on everyone I encounter 😉

**Comment by noopkat** [comment]
oh my gosh I had no idea what a pain this has been for y'all not having the standards from no linting!
I am more than happy to discuss a minimal set of rules. 

Whitespace, indent size and indent type would at the minimum be helpful I think. I'm going to suggest we look into a good tool for auto-fixing any lint errors with a pre-commit hook, then folks don't even have to care about it if they don't use the .editorconfig.

Thoughts? 🤔

**Comment by mpaarating** [comment]
@noopkat I like the pre-commit hook idea and the minimum for the .editorconfig!

**Comment by mtheoryx** [comment]
I do have another idea...

I'm reminded of this technique since I've been doing some docker environment variable (.env) work on a few other projects. Here's what I do:

- Add a .env file with some settings. Could be "minimum defaults" or could be blank API key stuff used more as an "example" for others to discover settings/configs they can use.
- Commit that "example" file
- Update .gitignore. This way if others modify it locally, it wont get caught up in the VCS

For our case, you could add some community-agreed minimum configuration. Follow the same pattern above, then let users update it locally however they want.

What do you think?

**Comment by noopkat** [comment]
@mtheoryx I like this approach a lot!

**Comment by underscoredotspace** [comment]
The only default that seems to be at odds with the existing code is single quotes.

**Comment by mtheoryx** [comment]
I think we can close this out, #66 does this. Cheers!
