### ISSUE TITLE
Support Docker for isolation, portability, and quick setup

### ISSUE THREAD

**Issue by mtheoryx** [noopkat/electric-io#44]
Opening this (and working on it) for the following reasons:

1. Isolation - no need to pollute your global with different versions of "stuff"
2. Portability - reduce "works on my machine" weirdness across environments
3. Quick setup - Minimize install requirements to quickly spin up an example

**Comment by mtheoryx** [comment]
I've made some great progress on this, should have a PR ready before next week's stream :)

**Comment by noopkat** [comment]
big ups on this, very excited! 🎉
