### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#5]
+ [x] Set up test framework
+ [x] Write tests
+ [x] Create `npm test` command

**Comment by underscoredotspace** [comment]
Hey @noopkat o/

I'd totally be up for setting up the framework and CI, and maybe writing tests if I have time. Do you have an opinion on frameworks? I tend to use Jest, which has really pushed me into TDD for my personal projects, but I see you use Tape. 

- colinfoldsfive

**Comment by mpaarating** [comment]
@underscoredotspace I'd love to see a Jest setup!

**Comment by noopkat** [comment]
@underscoredotspace heck yes! echoing @mpaarating - I'd love a Jest setup!

**Comment by underscoredotspace** [comment]
OMG, so much positivity for tests! 

I've submitted a pull request now, but it defo needs some amendments; if I could have some feedback I'll sort it out.

**Comment by escherina** [comment]
Just wanted to add that [vue-test-utils](https://github.com/vuejs/vue-test-utils) might be a good fit for testing the Vue components. Here's [an example of using it with Jest](https://github.com/vuejs/vue-test-utils-jest-example), since @underscoredotspace did such a good job getting Jest set up. And here are the [full docs](https://vue-test-utils.vuejs.org/).

**Comment by underscoredotspace** [comment]
@escherina, I've just tried Jest Snapshots for the first time, and if the components here render in a consistent way, you may not need to add additional utils. 

In my [Webtris](//github.com/underscoredotspace/webtris-js) project, I've got an object with a `render` method that returns the component markup, and all the test needs is `.toMatchSnapshot()`

```javascript
  test('render method', () => {
    expect.assertions(1)
    expect(board.render()).toMatchSnapshot()
  })
```

It creates a snapshot file the first time you run the test - super-simple. I'd hope there's an easy way to get Vue to return the markup directly.

**Comment by escherina** [comment]
@underscoredotspace That sounds ideal - I must admit I haven't tried vue-test-utils myself, so if it's overkill for this project, let's keep it simple.

**Comment by escherina** [comment]
I've merged in #34 - thanks for the great work on that, @underscoredotspace! We're all set up for testing now. Next step: writing tests!

**Comment by mtheoryx** [comment]
How do we want to handle issues and testing? I feel like having one issue to add all coverage is much too big to tackle.

Also, there are a few different focus areas that could use testing. UI, logic, simulation server, etc.

Curious to hear your thoughts, all!

**Comment by underscoredotspace** [comment]
I've tried to work out how to test the Vue components, but I'm not getting there. @noopkat in `CONTRIBUTING` you say shout if you're stuck, and I kinda (totally) am. Do you have any links to documentation that shows tests of the components in the style use here?

**Comment by mpaarating** [comment]
@underscoredotspace Not sure if you've seen this already or not, but [here](https://github.com/vuejs/vue-test-utils-jest-example) is the official example for Jest tests with vue! I haven't had time to test it yet myself, but the examples look straightforward enough.

**Comment by underscoredotspace** [comment]
@mpaarating yeah, I did check that out and it hasn't helped. I've tried this on a [branch](https://github.com/underscoredotspace/electric-io/tree/vue-test-utils) on my own repo for this if you fancy having a look. 

I think my problem is something simple I'm missing rather a requirement for vue-test-utils, but I may be wrong.

**Comment by mtheoryx** [comment]
@underscoredotspace I'm set up with your branch (and not a Vue guy, so bear with me).

https://vue-test-utils.vuejs.org/guides/#testing-single-file-components-with-jest

It looks like you're missing a few things from that guide up there ^^

Here are a few points I see differing:

- vue-jest
- Transform with vue-jest
- Babel transform for jest (I think that was there, but maybe you removed it?)

We aren't really using "the vue file" so some of that config is not needed, but I feel like we have a missing piece here.

Here is the working package.json from the project linked off that page, take a glance at how it differs from your setup: https://github.com/vuejs/vue-test-utils-jest-example/blob/master/package.json

**Comment by mtheoryx** [comment]
^^ I've played around with ideas, and I'm just as lost as you are, @underscoredotspace ! Reached out to some Vue folks, but rest assured, you are not alone in being baffled at the moment :)

**Comment by underscoredotspace** [comment]
I've tried a different approach of cloning the jest example repo and copying the number component from here and I'm getting the same error. 

It seems to be the way Vue is being loaded - in electric-io it's being loaded by the script tag, so we'd need to import it somewhere. Adding `import Vue from 'vue'` into `number.js` clears the error and allows the simple test to pass, but this isn't the solution as the code itself would need to be restructured. 

I've also tried adding Vue to the global object in Node as I've done in the past with Angular, but this doesn't work either. 

```javascript
import Vue from 'vue'
global.Vue = Vue // tried window.Vue also
```

I still don't think that vue-test-utils is strictly required and I didn't really want to add more deps anyway.

**Comment by escherina** [comment]
I can take a look this evening - I've now used vue-test-utils in two projects, so I have a bit of experience with it. (Unfortunately the projects aren't public code or I'd share them here.) 

@underscoredotspace, I see what you mean about the issue with the way Vue is imported into the project. I'm hopeful that there's a way to use vue-test-utils without changing the original project code (I've found it to be a really nice little library for testing component behaviour) but if not, we can definitely look for another solution. 🙂

**Comment by escherina** [comment]
And just to add: @underscoredotspace - you were so close with your solution, it was just that Jest needed a specific setup file for adding window.Vue. Seeing what you tried gave me a good idea what to try next!

![bitmoji](https://render.bitstrips.com/v2/cpanel/9ff55377-6e8f-4a55-9baf-471d1ee75e6a-fe2b87c9-121a-46aa-8177-02221b1823cc-v1.png?transparent=1&palette=1&width=246)

**Comment by underscoredotspace** [comment]
Wow, good work @escherina. I was really scratching my head!

**Comment by underscoredotspace** [comment]
I've adapted the above ever-so-slightly and added to my PR (#57). `babel-jest` will transform `.js` files by default and seems to only be needed if we needed to add the `.vue` transform.

**Comment by noopkat** [comment]
I'm going to close this, as @underscoredotspace and @jeffnhorner have contributed enough for this to be satisfied. Moar tests are always welcome, but we good for this issue! Thanks to everyone else who also helped this happen ❤️ 

![bitmoji](https://render.bitstrips.com/v2/cpanel/c48b9d8f-75a2-4765-8997-20be2c0d3345-8016a622-e09b-4505-8856-7726a074b1f9-v1.png?transparent=1&palette=1&width=246)
