### ISSUE TITLE
Environment option for debug/firehose?

### ISSUE THREAD

**Issue by mtheoryx** [noopkat/electric-io#54]
Suz turned off the firehose in simulation mode, but also mentioned a debug mode possibility?

We can really easily support that with env vars.

Thoughts?

[maintainers: a good label would just be "question" or something]. Cheers!

**Comment by mpaarating** [comment]
I think that makes sense. It'd be nice to move the simulating mode into that as well as part of the debug mode.

**Comment by noopkat** [comment]
I think this is a good idea! I might work on this during the stream today. Technically the simulating env var is already supported via the .env file. If that's not documented somewhere I'll also fix that too 😄

**Comment by mtheoryx** [comment]
Sounds awesome! I'll make for certain that any updates you make to the .env are picked up in the docker PR and supported out of the box.
