### ISSUE TITLE
Publish first Docker image to Docker Hub

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#55]
I need to fix my docker account fumbles, then I'll push and give the collaborators access if possible.

**Comment by mtheoryx** [comment]
Related to issue #52

**Comment by noopkat** [comment]
Am I doing this right 🤔 
https://hub.docker.com/r/noopkat/electric-io/

How do we 'productionize' it? I'm guessing we need to start versioning and cutting releases of electric-io etc.

**Comment by mtheoryx** [comment]
That can work!

We very much need to have a prod build and versioning. Can be another "spike" issue, if needed.

Glad you got this flow working though!
