### ISSUE TITLE
More heavily leverage Webpack for a more standard Vue setup

### ISSUE THREAD

**Issue by mpaarating** [noopkat/electric-io#59]
E-io has been a fantastically simple project for some time now, but I think we might be entering a point when using `.vue` files, transpilation, and a more traditional webapp setup (bring Vue in via `package.json`) would help developer efforts.

The testing issue is certainly an issue that seems to be tied to the way that Vue is imported in the project (I'm sure that there are ways around this and that someone can figure it out). Using `.vue` files would also give some useful syntax highlighting for those new to Vue and might help to lower the contributing barrier to entry.

Thoughts?

**Comment by mtheoryx** [comment]
I certainly see the issue with testing because of how we're loading in Vue. I think you may be onto something here @mpaarating 

I'm certainly not a Vue expert, but it's worth asking: Can we get away with fixing the testing issue without a wholesale change to making this an idiomatic "Vue app"?

And if so... what other issues down the road are we still going to be dealing with? Is going "Vue app" an inevitability?

**Comment by underscoredotspace** [comment]
The problem we had with testing the Vue components has been resolved, thanks to @escherina finding the missing piece, so I feel like this is _less_ of a barrier. 

This said, it would be easier for Vue newbies like myself to contribute more if the components were more idiomatic and matched what is shown in the documentation.

**Comment by mtheoryx** [comment]
Fantastic @escherina and @underscoredotspace !

**Comment by mtheoryx** [comment]
@mpaarating What do you think the first steps are? I think you're way more familiar with Vue than I am. Our mutual contact, Jeff, isn't listed in the Forks so I don't think he attempted a "conversion".

**Comment by mpaarating** [comment]
So I've not had a ton of time to look at it yet, but my thinking is to convert the vue component files to `.vue` files and then transpile/concat/minify. As its a day off, I'm hoping to get a good pass at this today.

**Comment by noopkat** [comment]
> my thinking is to convert the vue component files to .vue files and then transpile/concat/minify

Yep! This is what we need to do. It's not very glamorous work, but would improve the codebase a lot 😄 especially for potentially new contributors who are used to the more idiomatic vue way.

**Comment by mpaarating** [comment]
Made really good progress with this today. I got most of the app converted to `.vue` files, but ran into an issue late in the evening. I'm sure sleep will solve the issues.

**Comment by noopkat** [comment]
that's great. I watched part of your last stream and was grinning from ear to ear 😄 
this issue's work is a bit of a chore so I really appreciate all of the hard work 💯

**Comment by mtheoryx** [comment]
Also, hooray for a new streamer @mpaarating right, @noopkat ?! So awesome! You're inspiring a whole community!

**Comment by mtheoryx** [comment]
@mpaarating Your stream was great, this is going to be a very good thing!

**Comment by underscoredotspace** [comment]
The only other thing outstanding on this is documentation 📚. We refer to the previous style in CONTRIBUTING. Issue #50 also requires an update to this file. 

I'll assigned myself to both of these issues for now, but please speak up here if you would like to suggest content before I make a PR.

**Comment by mpaarating** [comment]
Good catch! Feel free to update the documentation. Thanks!

**Comment by mpaarating** [comment]
Closed by #71 Thanks again @underscoredotspace!
