### ISSUE TITLE
Background image tile feature

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#6]
Similar to specifying a background color for the dashboard, it'd also be great to specify a url that points to an image to tile as the background of the dashboard.

We could call the new dashboard property `bgImageUrl`

+ [ ] add background image option to settings form (a text input would be fine)
+ [ ] add background image property to dashboard.json (leave as empty string)
+ [ ] ensure property is saving to dashboard.json when saved in settings
+ [ ] ensure that the dashboard doesn't break if background image property is an empty string
+ [ ] ensure background image repeats or 'tiles' across the whole dashboard if it's a small image

Following a similar code strategy to the background color setting would be helpful.

Any questions - comment on this issue 🙇‍♀️

**Comment by escherina** [comment]
I can take this one!

Regarding the last point, what do you think about offering the user a "Repeat background" checkbox underneath a new Background Image URL field in the Settings? Maybe checked by default, as this seems like a more common use case. Alternatively, every background image could be tiled by default, but I like the idea of giving the user the option.

**Comment by noopkat** [comment]
Great! 🤩😎 thank you

I love the idea about the checkbox to have tiling be optional, please go for it!
