### ISSUE TITLE
Add tests to the express server! Yay!

### ISSUE THREAD

**Issue by mtheoryx** [noopkat/electric-io#76]
There are a few TODOs in the index.js of the express server file that are very valid!

```javascript
// TODO: break this file down into pieces so it's easier to digest
// ideas:
// 1. load routes from routes file
// 2. put routes handers in a file
// 3. put iot related work in a file
//
```

However, you cannot refactor untested code. That's just moving stuff arround. So this issue is to put some tests around the routes at least. THEN we can start moving stuff around :)

**Comment by noopkat** [comment]
YES. Awesome, thanks for raising this issue.

**Comment by mpaarating** [comment]
I'm gonna spend some time on this if its cool with everyone.

**Comment by mtheoryx** [comment]
I started down that path and got distracted/busy with other competing interests. Let me know if you want help or want to pair up.

**Comment by mpaarating** [comment]
@mtheoryx Will do! Thanks!

**Comment by mpaarating** [comment]
UPDATE: Believe it or not, I'm _still_ working on this. As in, I have read a bunch of blogs about route testing and am doing the route splitting and testing all in one! Yay ME!!!!! 

Downside is that @mtheoryx has me doing billable work most of the time so its coming along much slower than I anticipated.

**Note:** @mtheoryx is not my boss, but he an able body to throw in front of my lazy bus. Cheers!
