### ISSUE TITLE
Error: vue-template-compiler must be installed as a peer dependency

### ISSUE THREAD

**Issue by toolboc** [noopkat/electric-io#78]
Running from source using `npm start` without dev dependencies installed or attempting to run the docker image (which lacks dev dependencies)  results in:
`vue-template-compiler must be installed as a peer dependency`

![image](https://user-images.githubusercontent.com/2018336/45715560-21018a80-bb5a-11e8-8a80-102dd66424bb.png)

Oddly enough, the app appears to operate fine when this error is thrown.

Looks like this can be fixed by adding `vue-template-compiler` @ same version of `vue` to package.json

*PR incoming

**Comment by mtheoryx** [comment]
Thank you @toolboc for also taking a run at this! Looks like we both ended up at the correct solution in the end.

I'm going to go ahead and close this since we have it all fixed up now. Feel free to ping me if you have any questions!
