### ISSUE TITLE
Support nested payload properties

### ISSUE THREAD

**Issue by noopkat** [noopkat/electric-io#8]
When messages come in from devices, only top level properties will work.

For example, watching the `humidity` property within a card will work for this data:

```json
{ 
  "humidity": 45.698
}
```

But watching `humidity` in the data below is not possible:

```json
{ 
  "climate": {
     "humidity": 45.698
  }
}
```

Perhaps we can support nested properties! Or indexes in arrays also (maybe!)

**Comment by tkoster** [comment]
Hi Suz and friends,

Greetings from Melbourne Australia! Our time zones usually prevent me from catching the stream live but I love the code and chill vods :sparkles::coffee:.

Nested payload properties should be easy to support with the help of [JMESPath](http://jmespath.org/) and the [jmespath.js](https://github.com/jmespath/jmespath.js) library (0 dependencies, Apache-2.0). It's probably overkill (so power users might love it :nerd_face:) but it's very easy to integrate. Most importantly it is backwards compatible with the simple property names electric-io uses today.

I would be happy to contribute this :gift: . Are you interested in a pull request?

-- Thomas

**Comment by noopkat** [comment]
Hi @tkoster! Thanks for the kind words about the stream! I meant to look at this issue while streaming but in my absent mindedness I couldn't find it in Octobox. Sorry about that 🙇‍♀ 

I took at look at JMESPath and I love it for its simplicity, the fact that it has no dependencies, and that it has the exact kind of format to the query strings that I was hoping to support in electric-io. It would require very little change to the UI itself (just a link to JMESPath query docs for folks to learn) and would be a simple implementation on the Vue side too.

So, I'd LOVE a pull request. Thank you so much! 💯

**Comment by noopkat** [comment]
closing this thanks to @tkoster ❤️
